language: node_js
node_js: stable

sudo: true

#cache config
cache:
  directories:
    - "node_modules"

notifications:
  email:
    recipients:
      - zhangjingl02@126.com
    on_success: never
    on_failure: always

# S: Build Lifecycle
install:
  - npm install
#  - gem install travis
#  - travis login --pro --github-token ${GH_TOKEN}

before_script:
  - export TZ='Asia/Shanghai'
  - npm install -g gulp 
  - chmod +x _travis.sh

script:
  - hexo clean && hexo g
  - gulp 

after_success:
  - ./_travis.sh
 # - LAST_BUILD_NUMBER=68
 # - for i in $(seq 1 $LAST_BUILD_NUMBER ); do  travis logs $i --delete --force ; done

after_script:
  #- ./_travis.sh

# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/zhangjingl02/zhangjingl02.github.io.git

